config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'

  # Pages routes:
  get '/about', to: 'pages#about'

  # Responders routes:
  get '/responders/new', to: 'responders#new', as: 'new_responder'
  post '/responders', to: 'responders#create'

  # Messages routes:
  post 'messages/reply', to: 'messages#reply'
  # post 'messages/find_poll_addr', to: 'messages#find_poll_addr'

  get '*path', to: 'pages#index'

  # resource :messages do
  #   collection do
  #     post 'reply'
  #   end
  # end

end

app/views/pages/index.html.erb
<body id="page-top">

  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top"></nav>

  <header class="hero-container">
    <div class="container">
      <div class="row">
        <div class="col-sm-7">
          <div class="header-content">
            <div class="header-content-inner">
              <% if flash[:success] %>
                <p class="success">Thanks for signing up!</p>
              <% end %>
              <%= image_tag("Logos/voteraid_wordandlogomark_Whitemark.png", :class => 'heroimage') %>

              <%= link_to "Register as a Responder", new_responder_path, :method => :get, :class => "btn btn-outline btn-xl page-scroll btn-register" %>
              <div class="col-lg-12 text-center">
                <div class="section-heading heading-text">
                  <h2>Stop voter suppression at the source.</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <section id="features" class="features">
    <div class="container">
      <div class="row text-center">
        <div class="">
          <h2>VoterAid helps address the threat of voter suppression through:</h2>
          <div class="row">
            <div class="col-md-4 col-sm-6">
              <div class="table-logo">
                <%= image_tag("Logos/register.png", :class => 'about-table-image') %>
                <h4>
                  <strong>Registering</strong>
                </h4>
                <p>On-The-Ground Responders for Election Day.</p>
              </div>
            </div>

            <div class="col-md-4 col-sm-6">
              <div class="table-logo">
                <%= image_tag("Logos/respond.png", :class => 'about-table-image') %>
                <h4>
                  <strong>Responding</strong>
                </h4>
                <p>Immediately to instances of voter suppression.</p>
              </div>
            </div>

            <div class="col-md-4 col-sm-6">
              <div class="table-logo">
                <%= image_tag("Logos/inform.png", :class => 'about-table-image') %>
                <h4>
                  <strong>Informing</strong>
                </h4>
                <p>voters of their rights.</p>
              </div>
            </div>
          </div>
          <!-- /.row (nested) -->
        </div>
        <!-- /.col-lg-10 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->
  </section>

  <section class="cta">
    <div class="cta-content">
      <div class="container">
        <h2>Stop waiting.<br>Start helping.</h2>
        <%= link_to("Contribute on GitHub!", "https://github.com/Voter-Aid/voteraid", :method => :get, :class => "btn btn-outline btn-xl page-scroll")%>
      </div>
    </div>
    <div class="overlay"></div>
  </section>

  <footer>
    <div class="container">
      <p>&copy; 2016 Voteraid | Debug Politics SF Hackathon.</p>
    </div>
  </footer>

  <!-- jQuery -->
  <script src="vendor/jquery/jquery.min.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

  <!-- Plugin JavaScript -->
  <!-- Theme JavaScript -->
  <script src="js/new-age.min.js"></script>

</body>